ersion: '3.8'

services:
  db:
    image: postgres:13
    container_name: shareit_db
    environment:
      POSTGRES_USER: shareit
      POSTGRES_PASSWORD: shareit
      POSTGRES_DB: shareit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    entrypoint: ["/docker-entrypoint-initdb.d/init-db.sh"]

  app:
    build: .
    container_name: shareit_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shareit
      SPRING_DATASOURCE_USERNAME: shareit
      SPRING_DATASOURCE_PASSWORD: shareit
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs

volumes:
  postgres_data:
    driver: local